const NOW = '2026-02-25T00:00:00.000Z';

export const fixtures = {
  partners: [
    {
      id: 'p1',
      displayName: 'Acme Devices',
      regions: ['NA', 'EMEA'],
      countriesIso2: ['US', 'GB'],
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],

  partnerKeys: [
    {
      id: 'pk1',
      key: 'acme-stb-na',
      partnerId: 'p1',
      chipset: 'BCM7218',
      oem: 'Acme',
      kernel: null,
      os: null,
      countries: ['US'],
      regions: ['DOMESTIC'],
      isActive: true,
      source: 'manual',
      importBatchId: null,
      createdAt: NOW,
      createdBy: 'test-uid',
      updatedAt: NOW,
      updatedBy: 'test-uid',
    },
  ],

  devices: [
    {
      id: 'd1',
      displayName: 'Acme Streamer 4K',
      deviceId: 'acme-4k-001',
      partnerKeyId: 'pk1',
      deviceType: 'STB',
      status: 'active',
      liveAdkVersion: '7.3.1',
      certificationStatus: 'Certified',
      certificationNotes: null,
      lastCertifiedDate: NOW,
      questionnaireUrl: null,
      questionnaireFileUrl: null,
      activeDeviceCount: 150000,
      specCompleteness: 75,
      tierId: 't1',
      tierAssignedAt: NOW,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'd2',
      displayName: 'Claro Brazil HD Legacy',
      deviceId: 'claro-brazil-hd-legacy',
      partnerKeyId: '',
      deviceType: 'STB',
      status: 'active',
      liveAdkVersion: null,
      certificationStatus: 'Not Submitted',
      certificationNotes: null,
      lastCertifiedDate: null,
      questionnaireUrl: null,
      questionnaireFileUrl: null,
      activeDeviceCount: 8000,
      specCompleteness: 0,
      tierId: null,
      tierAssignedAt: null,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],

  deviceSpecs: [
    {
      id: 'ds1',
      deviceId: 'd1',
      general: { modelName: 'Streamer 4K', modelNumber: 'ACM-4K-001', dateDeployed: null, dateDeliveriesStopped: null, activeDevicesMonthly: '150000', totalInstalledBase: null, forecastedGrowth: null, countriesDeployed: 'US', thirdPartyApps: null, connectionType: null, connectionTypeOther: null },
      hardware: { socVendor: 'Broadcom', socVendorOther: null, socModelChipset: 'BCM7218', softwareArchitecture: null, softwareArchitectureOther: null, socBaseRefVersion: null, socCustomizations: null, socCustomizationsDesc: null, socSupportContract: null, socSupportExpiration: null, cpuClockRateGhz: 1.8, cpuDmips: '12000', cpuCores: '4', cpuCoresOther: null, stbManufacturer: 'Acme', operatingSystem: 'Linux', operatingSystemOther: null, osVersion: '5.4', osCustomization: null, osCustomizationDesc: null, middlewareProvider: null, middlewareProviderOther: null, middlewareVersion: null, middlewareContract: null, middlewareContractExpiration: null, middlewareIntegrationCompany: null, videoDelivery: null, videoDeliveryOther: null, memoryTotalGb: 2, memoryType: 'DDR4', memoryTypeOther: null, ramAvailableGb: 1.5, linuxMemoryAvailableMb: null, gpuMemoryAvailableMb: 512, gpuTextureMemoryMb: null, gpuMemorySharing: null, gpuMemorySharingOther: null, gpuMemoryReservedMb: null, storageTotalGb: 8, storageType: 'eMMC', storageTypeOther: null, storageAvailableMb: 4096, nonPersistentStorageMb: null, maxAppBinarySizeMb: null, filesystemType: null, filesystemTypeOther: null, storageLimitations: null, storageLimitationsDesc: null, gpuAvailability: null, gpuAvailableForApp: null, gpuGraphicsLibrary: null, gpuGraphicsLibraryOther: null, openglEs2Apps: null, openglEs2AppsNames: null, streamingInterface: null, streamingInterfaceOther: null, ethernetPort: null, wifiStandards: null, wifiBands: null, mocaPresent: null, maxStreamingThroughputMbps: null, hdmiCapabilitiesRetrieval: null, hdmiVersion: '2.1', hdmiVersionOther: null, digitalVideoOutputModes: null, analogVideoOutputModes: null, uiNativeResolution: '3840x2160', uiNativeResolutionOther: null, ottAppRestrictions: null },
      firmwareUpdates: { firmwareSupported: 'Yes', firmwareFrequency: null, firmwareFrequencyOther: null, internalLeadTime: null, rolloutDuration: null, emergencyUpdate: null, emergencyUpdateTime: null, codeSigning: null, codeSigningDesc: null },
      mediaCodec: { avcH264: 'Yes', hevcH265: 'Yes', eac3DolbyDigitalPlus: 'Yes', eac3Atmos: null, hdr10: 'Yes', hdr10Plus: null, av1: null, dolbyVisionSupported: null, dolbyVisionVersion: null },
      frameRates: { outputRefreshRates: '24/30/60', userRefreshRateSettings: null, frameRateAdjust: null, frameRateAdjustOther: null, frameRateConvert: null, frameRateConvertFixed: null, appDetermineRefreshRate: null, appSetRefreshRate: null },
      contentProtection: { drmSystem: null, encryptionScheme: null, playreadySupported: 'Yes', playreadyVersion: '4.0', playreadySecurityLevel: 'SL3000', playreadyEncryption: null, widevineSupported: 'Yes', widevineSecurityLevel: 'L1', widevineVersion: '16.0', widevineEncryption: null, drmHwLevel: null, cbcsSupport: null, multiKeyCtr: null, multiKeyCtrMax: null, digitalVideoOutput: null, hdcpVersion: '2.3', hdcpType: null, otherDrms: null, broadcomSage: null, secureFirmwareDownload: null, signedFirmwareSecureBoot: null, hardwareRootOfTrust: 'Yes', tamperResistantCode: null, tee: 'TrustZone', secureVideoPath: null, rootedDeviceProtection: null, appCodeSigning: null, sideloadingRestricted: null, digitalOutputProtection: null, encryptedAudio: null, secureBootJtag: null },
      native: { adkPortPossible: null, ursrModification: null, ursrModificationOther: null, nexusVideoApis: null, sageApiAccess: null, audioDetectionApi: null, drmBroadcomRefApi: null },
      videoPlayback: { avcBitrateLimitations: null, avcFrameRateLimitations: null, hevcBitrateLimitations: null, hevcFrameRateLimitations: null, eac3BitrateLimitations: null, playbackEncryption: null, playbackEncryptionOther: null, eac3MseCmaf: null, eac3DecodeMode: null, atmosSupported: null, dolbyVisionProfiles: null, dolbyVisionIdkSdkVersion: null, playreadyCdmVersion: null, playreadyCbcsConfirmed: null, widevineCdmVersion: null, widevineCdmCategory: null, widevineCbcsConfirmed: null, securitySecureBoot: 'Yes', securityHwRootOfTrust: 'Yes', securitySecureKeyStorage: null, securitySecureDecryption: null, securitySecureVideoPath: null, securityHdcp: null, html5CapabilityDetection: null },
      uhdHdr: { hdrTechnologies: 'HDR10', uhdSubscriberPercent: null, hdrNativeUi: null, displayRangeApi: null, displayRangeApiDesc: null, hdrTransform: null, hdrTransformOther: null, hdrModeSwitch: null, hdrModeSwitchOther: null, videoRangeRender: null, videoRangeRenderOther: null, hdrHelpResources: null, hdrUserSettings: null, colorSpace: null, colorSpaceOther: null, existingHdrApps: null, existingHdrAppsNames: null, publicHdrResources: null, hdrCompositing: null, graphicsPlaneResolution: null, graphicsPlaneResolutionOther: null },
      audioVideoOutput: { displayOutputSettings: null, videoDecodeSettings: null, audioDecodeSettings: null, aspectRatioSettings: null, uiResolutionSettings: null, alternateAudioPath: null, audioSyncSettings: null, audioSyncRange: null },
      other: { voltageRange: null, voltageRangeOther: null, rcuType: null, bluetoothPresent: null, bluetoothVersion: null, bluetoothVersionOther: null, bluetoothProfiles: null, bluetoothUsedFor: null, otherVideoOutputs: null, otherAudioOutputs: null, otherVideoOutputProtection: null, otherVideoOutputDisney: null },
      appRuntime: { webEngine: 'Cobalt', webEngineVersion: '25', adkVersion: '7.3.1', mseSupport: 'Yes', mseLimitations: null, emeSupport: 'Yes', emeLimitations: null, jsEngine: 'V8', jsEngineVersion: '11', jsEngineLimitations: null, wasmSupport: null, webglSupport: null, webCryptoSupport: null },
      audioCapabilities: { pcmChannels: null, pcmChannelsOther: null, audioSampleRates: null, audioBitDepths: null, dolbyAudio: null, dolbyAudioOther: null, dtsAudio: null, dtsAudioOther: null, btAudio: null, btAudioOther: null, audioBackgroundBehavior: null, audioBackgroundOther: null },
      accessibility: { ttsApi: null, ttsApiDesc: null, captionFormats: null, captionRendering: null, adTrackSupport: null, focusManagementApi: null },
      platformIntegration: { deepLinkSupport: null, deepLinkDesc: null, voiceAssistant: null, homeScreenIntegration: null, homeScreenDesc: null, continueWatching: null, continueWatchingDesc: null, universalSearch: null, universalSearchDesc: null, recommendationsTiles: null, appAutostart: null },
      performanceBenchmarks: { coldStartTime: null, warmStartTime: null, ttff: null, uiFrameRate: null, uiFrameRateOther: null, concurrentStreams: null, concurrentStreamsDesc: null, memoryBackground: null, benchmarkAvailable: null },
      updatedAt: NOW,
    },
  ],

  hardwareTiers: [
    {
      id: 't1',
      tierName: 'Tier 1',
      tierRank: 1,
      ramMin: 1024,
      gpuMin: 256,
      cpuSpeedMin: 1500,
      cpuCoresMin: 4,
      requiredCodecs: ['avc', 'hevc'],
      require64Bit: true,
      version: 1,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 't2',
      tierName: 'Tier 2',
      tierRank: 2,
      ramMin: 512,
      gpuMin: 128,
      cpuSpeedMin: 1000,
      cpuCoresMin: 2,
      requiredCodecs: ['avc'],
      require64Bit: false,
      version: 1,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],

  alerts: [
    {
      id: 'a1',
      type: 'unregistered_device',
      partnerKey: 'unknown-key',
      deviceId: 'unknown-device-001',
      firstSeen: NOW,
      lastSeen: NOW,
      uniqueDeviceCount: 500,
      status: 'open',
      dismissedBy: null,
      dismissReason: null,
      dismissedAt: null,
      consecutiveMisses: 3,
    },
  ],

  telemetrySnapshots: [
    {
      id: 'ts1',
      partnerKey: 'acme-stb-na',
      deviceId: 'acme-4k-001',
      coreVersion: '7.3.1',
      uniqueDevices: 1200,
      eventCount: 45000,
      snapshotDate: NOW,
    },
  ],

  auditLog: [
    {
      id: 'al1',
      entityType: 'device',
      entityId: 'd1',
      field: 'certificationStatus',
      oldValue: 'Pending',
      newValue: 'Certified',
      userId: 'test-uid',
      userEmail: 'test@disney.com',
      timestamp: NOW,
    },
  ],

  uploadHistory: [
    {
      id: 'uh1',
      uploadedBy: 'test-uid',
      uploadedByEmail: 'test@disney.com',
      uploadedAt: NOW,
      fileName: 'telemetry-2026-02.csv',
      rowCount: 100,
      successCount: 98,
      errorCount: 2,
      snapshotDate: NOW,
      errors: ['Row 50: invalid device', 'Row 75: invalid device'],
    },
  ],

  users: [
    {
      id: 'test-uid',
      email: 'test@disney.com',
      role: 'admin',
      displayName: 'Test User',
      photoUrl: null,
      lastLogin: NOW,
      updatedAt: null,
      updatedBy: null,
    },
    {
      id: 'user-2',
      email: 'viewer@disney.com',
      role: 'viewer',
      displayName: 'Viewer User',
      photoUrl: null,
      lastLogin: NOW,
      updatedAt: null,
      updatedBy: null,
    },
  ],

  deployments: [],
  deviceTierAssignments: [],
  config: [],

  questionnaireIntakeJobs: [
    {
      id: 'qj1',
      fileName: 'Acme_STB_Questionnaire.xlsx',
      fileStoragePath: 'questionnaires/qj1/Acme_STB_Questionnaire.xlsx',
      fileSizeBytes: 12345,
      uploadedBy: 'test-uid',
      uploadedByEmail: 'test@disney.com',
      uploadedAt: NOW,
      partnerId: 'p1',
      partnerConfidence: 0.95,
      partnerDetectionMethod: 'filename',
      questionnaireFormat: 'lg_stb_v1',
      deviceCountDetected: 1,
      status: 'pending_review',
      aiExtractionMode: 'auto',
      aiExtractionStartedAt: NOW,
      aiExtractionCompletedAt: NOW,
      extractionError: null,
      extractionStep: null,
      extractionCurrentDevice: null,
      devicesComplete: 1,
      devicesFailed: 0,
      notes: null,
      createdAt: NOW,
      updatedAt: NOW,
    },
    {
      id: 'qj2',
      fileName: 'LG_Questionnaire.xlsx',
      fileStoragePath: 'questionnaires/qj2/LG_Questionnaire.xlsx',
      fileSizeBytes: 8000,
      uploadedBy: 'test-uid',
      uploadedByEmail: 'test@disney.com',
      uploadedAt: NOW,
      partnerId: null,
      partnerConfidence: null,
      partnerDetectionMethod: null,
      questionnaireFormat: 'unknown',
      deviceCountDetected: 0,
      status: 'awaiting_extraction',
      aiExtractionMode: null,
      aiExtractionStartedAt: null,
      aiExtractionCompletedAt: null,
      extractionError: null,
      extractionStep: null,
      extractionCurrentDevice: null,
      devicesComplete: 0,
      devicesFailed: 0,
      notes: null,
      createdAt: NOW,
      updatedAt: NOW,
    },
  ],

  questionnaireStagedDevices: [
    {
      id: 'qsd1',
      intakeJobId: 'qj1',
      columnIndex: 3,
      rawHeaderLabel: 'STB Model A',
      detectedModelName: null,
      detectedModelNumber: null,
      detectedManufacturer: null,
      platformType: 'ncp_linux',
      isOutOfScope: false,
      matchedDeviceId: null,
      matchConfidence: null,
      matchMethod: null,
      reviewStatus: 'pending',
      reviewedBy: null,
      reviewedAt: null,
      rejectionReason: null,
      confirmedDisplayName: null,
      confirmedModelNumber: null,
      confirmedManufacturer: null,
      confirmedDeviceType: null,
      extractionStatus: 'complete',
      extractionError: null,
      createdAt: NOW,
    },
    {
      id: 'qsd2',
      intakeJobId: 'qj2',
      columnIndex: 3,
      rawHeaderLabel: 'LG Model B',
      detectedModelName: null,
      detectedModelNumber: null,
      detectedManufacturer: null,
      platformType: 'ncp_linux',
      isOutOfScope: false,
      matchedDeviceId: null,
      matchConfidence: null,
      matchMethod: null,
      reviewStatus: 'pending',
      reviewedBy: null,
      reviewedAt: null,
      rejectionReason: null,
      confirmedDisplayName: null,
      confirmedModelNumber: null,
      confirmedManufacturer: null,
      confirmedDeviceType: null,
      extractionStatus: 'pending',
      extractionError: null,
      createdAt: NOW,
    },
  ],

  questionnaireStagedFields: [
    {
      id: 'qsf1',
      stagedDeviceId: 'qsd1',
      intakeJobId: 'qj1',
      dstFieldKey: 'hardware.socVendor',
      dstFieldCategory: 'hardware',
      rawQuestionText: 'SoC Vendor?',
      rawAnswerText: 'Broadcom',
      extractedValue: 'Broadcom',
      extractionMethod: 'ai',
      aiConfidence: 0.95,
      aiReasoning: 'Direct answer',
      conflictStatus: 'new_field',
      existingValue: null,
      resolution: 'pending',
      resolvedBy: null,
      resolvedAt: null,
      createdAt: NOW,
    },
  ],

  notifications: [],
  deviceQuestionnaireSources: [],
};

export function seedAll(db: { seed: (name: string, docs: Array<{ id: string; [k: string]: unknown }>) => void }) {
  for (const [name, docs] of Object.entries(fixtures)) {
    db.seed(name, docs as Array<{ id: string; [k: string]: unknown }>);
  }
}
